<?php
/**
 * ACF param export
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56accb6eb23a6',
	'title' => 'Évènements',
	'fields' => array (
		array (
			'key' => 'field_56accb73cd5a0',
			'label' => 'Titre',
			'name' => 'uxr_event_title',
			'type' => 'text',
			'instructions' => 'Par exemple : UX Deiz #1, Afterwork #1, Ateliers #1… C\'est ce titre qui sera affiché à côté de la date en haut de page.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57011fc929e70',
			'label' => 'Type d\'évènement',
			'name' => 'uxr_event_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'afterwork' => 'Afterwork',
				'uxdeiz' => 'UX Deiz',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_56accbaecd5a2',
			'label' => 'Date de l\'évènement',
			'name' => 'uxr_event_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_56c8d8b6e0a57',
			'label' => 'Heure',
			'name' => 'uxr_event_time',
			'type' => 'text',
			'instructions' => 'Il est possible d\'indiquer l\'heure ou bien « À partir de… ».',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56accb82cd5a1',
			'label' => 'Thématique',
			'name' => 'uxr_event_theme',
			'type' => 'text',
			'instructions' => 'Par exemple : Au cœur de notre quotidien, Je t\'aime moi non plus…<br />
Utiliser une balise <code>&lt;span&gt;&lt;/span&gt;</code> pour mettre du texte en noir, et une balise <code>&lt;br /&gt;</code> pour forcer un retour à la ligne.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57011fc929e70',
						'operator' => '==',
						'value' => 'uxdeiz',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c8a3868d42c',
			'label' => 'Interventions',
			'name' => 'uxr_event_talks',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57011fc929e70',
						'operator' => '==',
						'value' => 'uxdeiz',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'talks',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56c8d27db7b93',
			'label' => 'Lien Meetup',
			'name' => 'uxr_event_tickets',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56c8d880e0a55',
			'label' => 'Notes complémentaires',
			'name' => 'uxr_event_notes_bottom',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'comments',
		2 => 'categories',
		3 => 'tags',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c8d0939720f',
	'title' => 'Interventions',
	'fields' => array (
		array (
			'key' => 'field_56c8d13e9f51f',
			'label' => 'Titre',
			'name' => 'uxr_talk_title',
			'type' => 'text',
			'instructions' => 'Seule la balise <code>&lt;br /&gt;</code> est autorisée.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c8d2f85fc39',
			'label' => 'Retranscription',
			'name' => 'uxr_talk_transcript',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Ajouter un bloc de contenu',
			'min' => 1,
			'max' => '',
			'layouts' => array (
				array (
					'key' => '56c8d3c1f0a08',
					'name' => 'subtitle',
					'label' => 'Sous-titre',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c8d3e754751',
					'name' => 'wysiwyg',
					'label' => 'WYSIWYG',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c8d3ec54752',
							'label' => 'WYSIWYG',
							'name' => 'wysiwyg',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56c8d416e09ae',
					'name' => 'fullwidth_image',
					'label' => 'Image pleine largeur',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56c8d424e09af',
							'label' => 'Image pleine largeur',
							'name' => 'fullwidth_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'uxr_speaker_medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56d3190471dad',
					'name' => 'links',
					'label' => 'Liens',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_56d3191171dae',
							'label' => 'Liens',
							'name' => 'links',
							'type' => 'repeater',
							'instructions' => 'Liens vers les slides, vers une vidéo, vers un site ou un blog…',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'row',
							'button_label' => 'Ajouter un lien',
							'sub_fields' => array (
								array (
									'key' => 'field_56d319717825d',
									'label' => 'Titre',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56d319787825e',
									'label' => 'URL',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_56c8d2ac5fc37',
			'label' => 'Durée',
			'name' => 'uxr_talk_duration',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c8d2c85fc38',
			'label' => 'Format',
			'name' => 'uxr_talk_format',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'conference' => 'Conférence',
				'atelier' => 'Atelier',
			),
			'default_value' => array (
				0 => 'conference',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'talks',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c8d6d2e7276',
	'title' => 'Lieux',
	'fields' => array (
		array (
			'key' => 'field_56c8d6e16ce1f',
			'label' => 'Adresse',
			'name' => 'uxr_place_address',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '48.117266',
			'center_lng' => '-1.6777925999999752',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_56c8d6f16ce20',
			'label' => 'Téléphone',
			'name' => 'uxr_place_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c8d6fb6ce21',
			'label' => 'Comment s\'y rendre ?',
			'name' => 'uxr_place_infos',
			'type' => 'textarea',
			'instructions' => 'Seule les balises <code>&lt;br /&gt;</code> et <code>&lt;strong&gt;</code> sont autorisées.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5702c735f937c',
			'label' => 'Photo',
			'name' => 'uxr_place_picture',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'event_place',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5713b43778d60',
	'title' => 'Options',
	'fields' => array (
		array (
			'key' => 'field_5713b43a97c97',
			'label' => 'Page « À propos » du site',
			'name' => 'uxr_about_page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_5713c06e6aace',
			'label' => 'Description des UX Deiz',
			'name' => 'uxr_ux_deiz_desc',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c8d44b8336e',
	'title' => 'Orateurs',
	'fields' => array (
		array (
			'key' => 'field_56c8d4f6df675',
			'label' => 'Photo',
			'name' => 'uxr_speaker_picture',
			'type' => 'image',
			'instructions' => 'Dimensions : <b>380x270</b>, mais pour le retina, c\'est mieux de prévoir <b>760x540</b>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 380,
			'min_height' => 270,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56c8d44fb6ead',
			'label' => 'URL Twitter',
			'name' => 'uxr_speaker_twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56c8d4d1df674',
			'label' => 'URL site web/blog',
			'name' => 'uxr_speaker_website',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56c8d50bdf676',
			'label' => 'Biographie',
			'name' => 'uxr_speaker_biography',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'talk_speakers',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c8d58b6fa48',
	'title' => 'Sponsors',
	'fields' => array (
		array (
			'key' => 'field_56c8d58e3b3e7',
			'label' => 'Logo',
			'name' => 'uxr_sponsor_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56c8d5993b3e8',
			'label' => 'Liens',
			'name' => 'uxr_sponsor_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Ajouter un lien',
			'sub_fields' => array (
				array (
					'key' => 'field_56c8d6147b701',
					'label' => 'Titre du lien',
					'name' => 'link_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c8d61e7b702',
					'label' => 'URL',
					'name' => 'link_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'event_sponsor',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;